// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'alert-export-canceled'
  | 'alert-export-error'
  | 'alert-export-none'
  | 'alert-export-success'
  | 'dialog-cancel'
  | 'dialog-confirm'
  | 'dialog-description'
  | 'dialog-title'
  | 'menuitem-current-label'
  | 'menuitem-label'
  | 'menuitem-selected-label'
  | 'pref-csv-fields-order'
  | 'pref-csv-fields-selection'
  | 'pref-csv-fields-title'
  | 'pref-export-format'
  | 'pref-help'
  | 'pref-target-highlight-color'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
